# Generated by Django 5.1.1 on 2024-10-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Boost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("duration", models.IntegerField()),
                ("power", models.IntegerField()),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="task1.boosttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("points", models.IntegerField(default=0)),
                ("first_login", models.DateTimeField(auto_now_add=True)),
                (
                    "bonuses",
                    models.ManyToManyField(
                        blank=True, related_name="bonuses", to="task1.boost"
                    ),
                ),
            ],
        ),
    ]
