# Generated by Django 5.1.1 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boost",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="boosttype",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
